class AuditAction:
    PRODUCT_CREATED = "PRODUCT_CREATED"
    PRODUCT_UPDATED = "PRODUCT_UPDATED"
    PRODUCT_ACTIVATED = "PRODUCT_ACTIVATED"
    PRODUCT_DEACTIVATED = "PRODUCT_DEACTIVATED"
    PRODUCT_PRICE_CHANGED = "PRODUCT_PRICE_CHANGED"
