# Generated by Django 4.2.11 on 2025-08-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysvar_app', '0002_cliente_codigos_colecao_compra_contabancaria_cor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codigos',
            name='variavel',
        ),
        migrations.AddField(
            model_name='codigos',
            name='colecao',
            field=models.CharField(default='00', max_length=2),
        ),
        migrations.AddField(
            model_name='codigos',
            name='estacao',
            field=models.CharField(default='00', max_length=2),
        ),
    ]
