# Generated by Django 4.2.11 on 2025-08-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysvar_app', '0003_remove_codigos_variavel_codigos_colecao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='Margem',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
