# Generated by Django 4.2.11 on 2025-08-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysvar_app', '0004_familia_margem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigos',
            name='valor_var',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='codigos',
            unique_together={('colecao', 'estacao')},
        ),
    ]
