# Generated by Django 4.2.11 on 2025-08-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysvar_app', '0005_alter_codigos_valor_var_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='codigos',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='codigos',
            name='valor_var',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='produto',
            name='referencia',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='codigos',
            constraint=models.UniqueConstraint(fields=('colecao', 'estacao'), name='unique_colecao_estacao'),
        ),
    ]
