# Generated by Django 4.2.11 on 2025-08-22 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysvar_app', '0006_alter_codigos_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Caixa', 'Caixa'), ('Gerente', 'Gerente'), ('Admin', 'Admin'), ('Auxiliar', 'Auxiliar'), ('Assistente', 'Assistente')], default='Regular', max_length=10),
        ),
    ]
