# Generated by Django X.Y on 2025-08-30 00:00

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('sysvar_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Idloja',
            field=models.ForeignKey(
                related_name='usuarios',
                to='sysvar_app.loja',
                null=True, blank=True,
                on_delete=django.db.models.deletion.SET_NULL
            ),
        ),
    ]
