# Generated by Django 4.2.11 on 2025-10-07 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sysvar_app', '0002_produto_ativo_produto_inativado_em_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recebimentopcitem',
            name='Idcompraitem',
        ),
    ]
