# Generated by Django 4.2.11 on 2025-09-02 01:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sysvar_app', '0002_user_loja_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFeEntrada',
            fields=[
                ('Idnfe', models.BigAutoField(primary_key=True, serialize=False)),
                ('chave', models.CharField(max_length=44, unique=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('serie', models.CharField(blank=True, max_length=5, null=True)),
                ('dhEmi', models.DateTimeField(blank=True, null=True)),
                ('cnpj_emitente', models.CharField(blank=True, max_length=14, null=True)),
                ('razao_emitente', models.CharField(blank=True, max_length=120, null=True)),
                ('xml', models.TextField(blank=True, null=True)),
                ('vProd', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('vDesc', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('vFrete', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('vOutro', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('vIPI', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('vICMSST', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('vNF', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status', models.CharField(default='importada', max_length=20)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('Idfornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sysvar_app.fornecedor')),
                ('Idloja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sysvar_app.loja')),
            ],
        ),
        migrations.CreateModel(
            name='NFeItem',
            fields=[
                ('Idnfeitem', models.BigAutoField(primary_key=True, serialize=False)),
                ('ordem', models.IntegerField()),
                ('cProd', models.CharField(max_length=60)),
                ('xProd', models.CharField(max_length=255)),
                ('ncm', models.CharField(blank=True, max_length=20, null=True)),
                ('cfop', models.CharField(blank=True, max_length=10, null=True)),
                ('uCom', models.CharField(blank=True, max_length=10, null=True)),
                ('qCom', models.DecimalField(decimal_places=3, max_digits=18)),
                ('vUnCom', models.DecimalField(decimal_places=6, max_digits=18)),
                ('vProd', models.DecimalField(decimal_places=2, max_digits=18)),
                ('cean', models.CharField(blank=True, max_length=20, null=True)),
                ('vDesc', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('vFrete', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('vOutro', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('nfe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='sysvar_app.nfeentrada')),
            ],
            options={
                'indexes': [models.Index(fields=['cean'], name='sysvar_app__cean_b2cbd2_idx'), models.Index(fields=['cProd'], name='sysvar_app__cProd_5ad583_idx'), models.Index(fields=['nfe', 'ordem'], name='sysvar_app__nfe_id_1a96dc_idx')],
            },
        ),
    ]
