# Generated by Django 4.2.11 on 2025-10-07 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sysvar_app', '0003_remove_recebimentopcitem_idcompraitem'),
    ]

    operations = [
        # 1) Remover o CHECK que referencia as colunas de CompraItem.
        migrations.RemoveConstraint(
            model_name='compraitem',
            name='compraitem_sku_xor_prod',
        ),

        # 2) Apagar a tabela CompraItem inteira (assim caem colunas e índices de uma vez).
        migrations.DeleteModel(
            name='CompraItem',
        ),

        # 3) Apagar a tabela Compra.
        migrations.DeleteModel(
            name='Compra',
        ),
    ]
