# Generated by Django 4.2.11 on 2025-09-02 01:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sysvar_app', '0003_nfeentrada_nfeitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='FornecedorSkuMap',
            fields=[
                ('Idmap', models.BigAutoField(primary_key=True, serialize=False)),
                ('cProd_vendor', models.CharField(max_length=60)),
                ('descricao_vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='desconto_rateado',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='frete_rateado',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='nfe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compra', to='sysvar_app.nfeentrada'),
        ),
        migrations.AddField(
            model_name='compra',
            name='outros_rateado',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='compraitem',
            name='Idprodutodetalhe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sysvar_app.produtodetalhe'),
        ),
        migrations.AddField(
            model_name='compraitem',
            name='custo_unitario',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='compraitem',
            name='frete_rateado_item',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='compraitem',
            name='outros_rateado_item',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='compraitem',
            name='Descontoitem',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='compraitem',
            name='Idproduto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sysvar_app.produto'),
        ),
        migrations.AddIndex(
            model_name='compraitem',
            index=models.Index(fields=['Idcompra'], name='sysvar_app__Idcompr_8b2609_idx'),
        ),
        migrations.AddIndex(
            model_name='compraitem',
            index=models.Index(fields=['Idprodutodetalhe'], name='sysvar_app__Idprodu_26e8e1_idx'),
        ),
        migrations.AddIndex(
            model_name='compraitem',
            index=models.Index(fields=['Idproduto'], name='sysvar_app__Idprodu_b80267_idx'),
        ),
        migrations.AddConstraint(
            model_name='compraitem',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('Idproduto__isnull', True), ('Idprodutodetalhe__isnull', False)), models.Q(('Idproduto__isnull', False), ('Idprodutodetalhe__isnull', True)), _connector='OR'), name='compraitem_sku_xor_prod'),
        ),
        migrations.AddField(
            model_name='fornecedorskumap',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sysvar_app.fornecedor'),
        ),
        migrations.AddField(
            model_name='fornecedorskumap',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sysvar_app.produto'),
        ),
        migrations.AddField(
            model_name='fornecedorskumap',
            name='produtodetalhe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sysvar_app.produtodetalhe'),
        ),
        migrations.AddIndex(
            model_name='fornecedorskumap',
            index=models.Index(fields=['fornecedor', 'cProd_vendor'], name='sysvar_app__fornece_5cf6ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='fornecedorskumap',
            constraint=models.UniqueConstraint(fields=('fornecedor', 'cProd_vendor'), name='uq_fornecedor_cprod'),
        ),
    ]
