# Generated by Django 4.2.11 on 2025-10-08 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sysvar_app', '0004_remove_compraitem_idcompra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocompra',
            name='aprovado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pc_aprovados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='condicao_pagamento',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='condicao_pagamento_detalhe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='fornecedor_contato',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='frete_previsto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='outros_previstos',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='parcelas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='percentual_desconto_global',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='tipo_pedido',
            field=models.CharField(choices=[('revenda', 'Revenda'), ('consumo', 'Uso/Consumo')], default='revenda', max_length=15),
        ),
        migrations.AddField(
            model_name='pedidocompraitem',
            name='data_entrega_prevista',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='Status',
            field=models.CharField(blank=True, choices=[('AB', 'Aberto'), ('AP', 'Aprovado'), ('RC', 'Recebendo'), ('CL', 'Concluído'), ('CA', 'Cancelado')], default='AB', max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='PedidoCompraEntrega',
            fields=[
                ('Idpc_entrega', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_entrega', models.DateField()),
                ('quantidade_prevista', models.IntegerField(blank=True, null=True)),
                ('observacao', models.CharField(blank=True, max_length=200, null=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='sysvar_app.pedidocompra')),
            ],
            options={
                'indexes': [models.Index(fields=['pedido', 'data_entrega'], name='sysvar_app__pedido__2e8939_idx')],
            },
        ),
    ]
