# Generated by Django 4.2.11 on 2025-10-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysvar_app', '0005_pedidocompra_aprovado_em_pedidocompra_aprovado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocompra',
            name='Status',
            field=models.CharField(blank=True, choices=[('AB', 'Aberto'), ('AP', 'Aprovado'), ('RC', 'Recebendo'), ('CL', 'Concluído'), ('CA', 'Cancelado'), ('AT', 'Atendido'), ('PA', 'Parcialmente (Aberto)'), ('PE', 'Parcialmente (Encerrado)')], default='AB', max_length=2, null=True),
        ),
    ]
