# Generated by Django 4.2.11 on 2025-10-10 17:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sysvar_app', '0006_alter_pedidocompra_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoCompraParcela',
            fields=[
                ('Idpc_parcela', models.BigAutoField(primary_key=True, serialize=False)),
                ('parcela', models.IntegerField()),
                ('prazo_dias', models.IntegerField(blank=True, null=True)),
                ('vencimento', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=18)),
                ('forma', models.CharField(blank=True, max_length=30, null=True)),
                ('observacao', models.CharField(blank=True, max_length=200, null=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas_rel', to='sysvar_app.pedidocompra')),
            ],
            options={
                'indexes': [models.Index(fields=['pedido', 'vencimento'], name='sysvar_app__pedido__2fcf26_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='pedidocompraparcela',
            constraint=models.UniqueConstraint(fields=('pedido', 'parcela'), name='uq_pc_parcela_numero'),
        ),
    ]
