# Generated by Django 4.2.11 on 2025-10-10 17:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sysvar_app', '0007_pedidocompraparcela_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('Idformapagamento', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descricao', models.CharField(max_length=120)),
                ('num_parcelas', models.IntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='FormaPagamentoParcela',
            fields=[
                ('Idformapagparcela', models.BigAutoField(primary_key=True, serialize=False)),
                ('ordem', models.IntegerField()),
                ('dias', models.IntegerField()),
                ('percentual', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('valor_fixo', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('forma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='sysvar_app.formapagamento')),
            ],
            options={
                'indexes': [models.Index(fields=['forma', 'ordem'], name='sysvar_app__forma_i_2a7bca_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='formapagamentoparcela',
            constraint=models.UniqueConstraint(fields=('forma', 'ordem'), name='uq_formapag_parcela_ordem'),
        ),
    ]
