# Generated by Django 4.2.11 on 2025-10-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysvar_app', '0008_formapagamento_formapagamentoparcela_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colecao',
            name='Estacao',
            field=models.CharField(blank=True, choices=[('01', 'Primavera'), ('02', 'Verão'), ('03', 'Outono'), ('04', 'Inverno')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='colecao',
            name='Status',
            field=models.CharField(blank=True, choices=[('CR', 'Criação'), ('PD', 'Produção'), ('AT', 'Ativa'), ('EN', 'Encerrada'), ('AR', 'Arquivada')], max_length=10, null=True),
        ),
    ]
