# Generated by Django 4.2.11 on 2025-10-20 15:19

from django.db import migrations, models
import django.db.models.constraints
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sysvar_app', '0009_alter_colecao_estacao_alter_colecao_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=80, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packs', to='sysvar_app.grade')),
            ],
            options={
                'db_table': 'sysvar_app_pack',
            },
        ),
        migrations.AddField(
            model_name='pedidocompraitem',
            name='n_packs',
            field=models.PositiveIntegerField(blank=True, help_text='Multiplicador de packs neste item.', null=True),
        ),
        migrations.AddField(
            model_name='pedidocompraitem',
            name='qtd_total_pack',
            field=models.PositiveIntegerField(blank=True, help_text='Quantidade total derivada do pack (n_packs × soma dos tamanhos do pack).', null=True),
        ),
        migrations.AddField(
            model_name='pedidocompraitem',
            name='pack',
            field=models.ForeignKey(blank=True, help_text='Pack aplicado a este item (opcional).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedido_itens', to='sysvar_app.pack'),
        ),
        migrations.CreateModel(
            name='PackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.PositiveIntegerField()),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='sysvar_app.pack')),
                ('tamanho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packs_itens', to='sysvar_app.tamanho')),
            ],
            options={
                'db_table': 'sysvar_app_pack_item',
                'indexes': [models.Index(fields=['pack'], name='ix_packitem_pack'), models.Index(fields=['tamanho'], name='ix_packitem_tamanho')],
            },
        ),
        migrations.AddConstraint(
            model_name='packitem',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('pack', 'tamanho'), name='uq_packitem_pack_tamanho'),
        ),
        migrations.AddIndex(
            model_name='pack',
            index=models.Index(fields=['grade'], name='ix_pack_grade'),
        ),
        migrations.AddIndex(
            model_name='pack',
            index=models.Index(fields=['ativo'], name='ix_pack_ativo'),
        ),
        migrations.AddConstraint(
            model_name='pack',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('grade', 'nome'), name='uq_pack_grade_nome'),
        ),
    ]
