# Generated by Django 4.2.11 on 2025-10-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysvar_app', '0010_pack_pedidocompraitem_n_packs_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pack',
            name='uq_pack_grade_nome',
        ),
        migrations.RemoveConstraint(
            model_name='packitem',
            name='uq_packitem_pack_tamanho',
        ),
        migrations.AddConstraint(
            model_name='pack',
            constraint=models.UniqueConstraint(fields=('grade', 'nome'), name='uq_pack_grade_nome'),
        ),
        migrations.AddConstraint(
            model_name='packitem',
            constraint=models.UniqueConstraint(fields=('pack', 'tamanho'), name='uq_packitem_pack_tamanho'),
        ),
    ]
