# Generated by Django 4.2.11 on 2025-10-07 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('username_snapshot', models.CharField(blank=True, max_length=150, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, max_length=64, null=True)),
                ('model', models.CharField(db_index=True, max_length=100)),
                ('object_id', models.CharField(db_index=True, max_length=64)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('custom', 'Custom'), ('status_change', 'Status Change')], db_index=True, default='custom', max_length=32)),
                ('changes_json', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['model', 'object_id', 'ts'], name='audit_model_obj_ts'), models.Index(fields=['user', 'ts'], name='audit_user_ts')],
            },
        ),
    ]
