# Generated by Django 4.2.11 on 2025-09-25 18:51

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_name', models.CharField(blank=True, max_length=150, null=True)),
                ('actor_role', models.CharField(blank=True, max_length=80, null=True)),
                ('loja_id', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(default='ui', max_length=20)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('request_id', models.UUIDField(blank=True, default=None, null=True)),
                ('model', models.CharField(max_length=80)),
                ('resource_id', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=40)),
                ('reason', models.TextField(blank=True, null=True)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'indexes': [models.Index(fields=['model', 'resource_id', 'created_at'], name='idx_audit_model_res'), models.Index(fields=['action', 'created_at'], name='idx_audit_action'), models.Index(fields=['created_at'], name='idx_audit_created_at'), models.Index(fields=['loja_id', 'created_at'], name='idx_audit_loja'), models.Index(fields=['actor', 'created_at'], name='idx_audit_actor'), django.contrib.postgres.indexes.GinIndex(fields=['before'], name='gin_audit_before'), django.contrib.postgres.indexes.GinIndex(fields=['after'], name='gin_audit_after')],
            },
        ),
    ]
