# Generated by Django 4.2.11 on 2025-09-25 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='gin_audit_before',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='gin_audit_after',
        ),
    ]
