# Generated by Django 4.2.11 on 2025-09-25 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auditoria', '0002_remove_auditlog_gin_audit_before_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='idx_audit_model_res',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='idx_audit_action',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='idx_audit_created_at',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='idx_audit_loja',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='idx_audit_actor',
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='ip',
            new_name='ip_address',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='action',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='actor_role',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='loja_id',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='model',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='source',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='action_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor_email',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='diff',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='resource_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='resource_ref',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='resource_type',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='request_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='resource_id',
            field=models.BigIntegerField(),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['resource_type', 'resource_id', 'created_at'], name='idx_audit_rt_rid_dt'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['resource_type', 'resource_ref', 'created_at'], name='idx_audit_rt_rref_dt'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action_name', 'created_at'], name='idx_audit_action_dt'),
        ),
    ]
